import { existsSync, readdirSync, readFileSync } from 'fs';

/**
 * Network identity (ports) of a validator node, stored inside its
 * keys/validator-N.json. Used only so a node knows which ports to bind —
 * finding OTHER nodes is the job of the bootnode / peer table (peerTable.ts).
 */
export interface NodeInfo {
  validatorIndex: number;
  apiPort: number;
  p2pPort: number;
}

const KEY_FILE_RE = /^validator-(\d+)\.json$/;

function isPort(n: unknown): n is number {
  return Number.isInteger(n) && (n as number) >= 1 && (n as number) <= 65535;
}

/**
 * Scans `dir` for validator-N.json files and returns each one's NodeInfo,
 * sorted by validator index.
 *
 * Throws with a clear message on a stale/malformed file (e.g. one generated
 * before ports were stored in it) — the fix is `npm run reset`.
 */
export function discoverValidatorNodes(dir = 'keys'): NodeInfo[] {
  if (!existsSync(dir)) return [];

  const nodes: NodeInfo[] = [];
  for (const file of readdirSync(dir)) {
    const match = KEY_FILE_RE.exec(file);
    if (!match) continue;

    const fileIndex = Number(match[1]);
    const path = `${dir}/${file}`;

    let info: any;
    try {
      info = JSON.parse(readFileSync(path, 'utf-8'))?.node;
    } catch {
      throw new Error(`${path} is not valid JSON`);
    }

    if (!info || !isPort(info.apiPort) || !isPort(info.p2pPort) || !Number.isInteger(info.validatorIndex)) {
      throw new Error(
        `${path} has no valid "node" section (validatorIndex/apiPort/p2pPort). ` +
        'It was probably generated by an older version — run `npm run reset`.'
      );
    }
    if (info.validatorIndex !== fileIndex) {
      throw new Error(`${path} says validatorIndex ${info.validatorIndex} but its filename says ${fileIndex}`);
    }

    nodes.push({ validatorIndex: info.validatorIndex, apiPort: info.apiPort, p2pPort: info.p2pPort });
  }

  return nodes.sort((a, b) => a.validatorIndex - b.validatorIndex);
}